{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  SYNAPSE_USER: {{ .Values.auth.username | quote }}
  SYNAPSE_PASSWORD: {{ .Values.auth.password | quote }}
{{- end }}
{{- if and .Values.tier.licenseKey (not .Values.tier.existingLicenseSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  SYNAPSE_LICENSE_KEY: {{ .Values.tier.licenseKey | quote }}
{{- end }}
{{- if and .Values.externalAuth.enabled .Values.externalAuth.config (not .Values.externalAuth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}-external-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  external-auth.toml: |
    {{- tpl .Values.externalAuth.config . | nindent 4 }}
{{- end }}
